### PR TITLE
Sensitivity depth small improvements

### PR DESCRIPTION
**Pull request by ReinhardPrix**
SensitivityDepthStackSlide: add feature to constrain cosi, psi priors (needed for paper)

### CODE REVIEW

**Review by kwwette — DISMISSED** [review]

**Comment by ReinhardPrix** [comment]
I've just fixed the documentation failure, will re-approve myself as trivial change from previous pull request

**Comment by ReinhardPrix** [comment]
damn, turns out I can't approve my own requests ...

**Comment by ReinhardPrix** [comment]
Apologies, @kwwette , I suspect I've messed up the workflow here, as github says you had some review comments (possibly fixed the typo already), but I didn't see it and now seems I can't see it any more as I force-pushed my fixed commits back on the branch ... I'll have to look more closely next time.

**Review by kwwette — DISMISSED** [review]

**Comment by ReinhardPrix** [comment]
3rd commit is just testing if travis timeout is the problem with the Mac build (see https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)

**Comment by ReinhardPrix** [comment]
giving up, don't know how to get this 'travis wait' thing to work. I've re-pushed the branch without any travis mucking, will leave as is for now, maybe re-trigger the build will work eventually if it's really just a timeout.

**Review by kwwette — APPROVED** [review]

**Comment by ReinhardPrix** [comment]
@kwwette any idea what's going wrong with the checks on mac-osx? I don't think it seems to be related to these changes, but the error persists and I don't think we've seen this before. It looks like a timeout, but I'm not sure where actually

**Pull request merged**
