### PR TITLE
Add workflow to build and publish docker image

### PR DESCRIPTION
**Pull request by Rodrigo-Tenorio**
This workflow builds up the docker container provided in this repo and publishes it so that it can be readily used.

@ReinhardPrix @kwwette any interest / inquire on this?

### CODE REVIEW

**Comment by kwwette** [comment]
@Rodrigo-Tenorio Thanks, this looks useful. 2 issues:

* The regular CI build is currently broken because it's using a too-new Ubuntu version. I'll have a look a fixing that and then ask you to rebase.
* The [Docker publishing job is failing](https://github.com/octapps/octapps/actions/runs/4269255834/jobs/7449451939):
```
------
 > exporting to GitHub cache:
------
ERROR: failed to solve: error writing layer blob: Patch "https://artifactcache.actions.githubusercontent.com/n6BhlYUj0sFUXw1uZP7oBzvZjqG8uIPEcDMf3ViLDljB16qer4/_apis/artifactcache/caches/12": read tcp 172.17.0.2:49994->13.107.43.16:443: read: connection reset by peer
Error: buildx failed with: ERROR: failed to solve: error writing layer blob: Patch "https://artifactcache.actions.githubusercontent.com/n6BhlYUj0sFUXw1uZP7oBzvZjqG8uIPEcDMf3ViLDljB16qer4/_apis/artifactcache/caches/12": read tcp 172.17.0.2:49994->13.107.43.16:443: read: connection reset by peer
```
Any ideas? Have you tested this yourself, e.g. on your own fork?

**Comment by kwwette** [comment]
@Rodrigo-Tenorio The regular CI build should now be fixed. Try rebasing you PR branch, and then see if you can fix the error in the Docker publishing job.

**Comment by Rodrigo-Tenorio** [comment]
Hi @kwwette , thanks, already rebased.

I did try it in my fork and [it did work](https://github.com/Rodrigo-Tenorio/octapps/pkgs/container/octapps). I'll re-run the action and check again the yml code.

**Comment by Rodrigo-Tenorio** [comment]
@kwwette , I apparently need approval for these workflows to run?

**Review by kwwette — APPROVED** [review]

**Comment by kwwette** [comment]
@Rodrigo-Tenorio I've run the workflows and it now passes - must have been a transient failure before. I'll approve and merge this. Thanks again!

**Pull request merged**
