### PR TITLE
Fix tests by reverting some sensitivity optimization commits

### PR DESCRIPTION
**Pull request by ReinhardPrix**
Trying to fix the failing tests by
- reverting 3 commits to the sensitivity-optimization framework: 
   70694d9397fc74ed43f8a20f8b4f974fd11dfb02: "OptimalSolution4StackSlide_v2.m: use fixed, user-customisable step size"
   c8be10a36870131e2d6a2c73bc2506e0382f951d: "OptimalSolution4StackSlide_v2_helpers.m: round up number of segments"
   028a25eba62d38107d5cb2b8540b7a918d71d0e1: "LocalCostCoefficients_v2.m: round up number of dimensions"

- adding a dummy test to WeaveCostFunctions()

### CODE REVIEW

**Comment by ReinhardPrix** [comment]
mh :thinking: ... not sure what's going on with the travis-CI ... taking quite a while to even start up?

**Comment by ReinhardPrix** [comment]
ahhh, ok, so https://travis-ci.org/github/octapps/octapps now says
`Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. ` ... nice. :see_no_evil: 
@kwwette are you familiar with this setup to be able to migrate this to the 'new' travis?

**Comment by kwwette** [comment]
@ReinhardPrix Unfortunately Travis CI is no longer free-as-in-beer :beer: :moneybag: :beer: :moneybag: :beer: :moneybag:

Fortunately GitHub has (apparently since 2018) its own CI called GitHub Actions, so I've ported over the Travis CI setup to this system. The build jobs are still largely the same:

- **build_docker** runs the `Dockerfile` which builds on Debian stretch, which is old enough that SWIG and Octave still work together, plus have Debian packages of LALSuite, so this job has the most complete test suite
- **build_linux** builds on a recent Ubuntu, which appears to build the SWIG extensions fine, but with no LALSuite packages, so some tests won't run
- **build_macosx** currently doesn't do much, since Octave from Homebrew is new enough that even the non-SWIG extensions are broken, and so the test suite probably won't run. I've kept the job anyway in case someone wants to fix this in future.
- **build_docs** builds the documentation and (on the _master_ branch of _octapps/octapps_) deploys it to https://octapps.github.io/

You'll need to rebase your branch on master to get the CI related changes. There might be some other failing tests, e.g. on the **build_linux** job, which appear to be changes in Octave itself. I'll leave it to you to fix those :grin:

**Comment by ReinhardPrix** [comment]
@kwwette awesome, thanks!

**Comment by ReinhardPrix** [comment]
:tada: now at least all current tests are passing.

@kwwette shall we merge this?

**Comment by kwwette** [comment]
Thanks @ReinhardPrix for the fixes. Can you first `rebase -i` to squash the `fixup!` commit? I'll then approve.

**Comment by ReinhardPrix** [comment]
yep, done.

**Review by kwwette — APPROVED** [review]

**Pull request merged**
